### ISSUE TITLE
Patient and Caregiver Routes

### ISSUE THREAD

**Issue by Teller35** [Teller35/med-planner#3]
**Description**
- Add the CRUD routes for the Patient and Caregiver models.
- Add the login and logout routes for the Patient and Caregiver models.

**Expectations**
- GET routes to return all patients and caregivers
- GET routes to return a single patient and caregiver
- POST routes to add a patient and caregiver
- POST routes to login to patient and caregiver
- POST routes to logout of patient and caregiver
- PUT routes to update a patient and caregiver
- DELETE routes to remove a patient and caregiver

**Comment by SirUbu** [comment]
Created branch `03-patient-caregiver-routes`.

**Comment by SirUbu** [comment]
Met expectations. Merged to `develop` branch.
