### ISSUE TITLE
Server - Initial Setup

### ISSUE THREAD

**Issue by Teller35** [Teller35/med-planner#5]
**Description**
- Logic for the server
- Set up connection.js file
- Set up server.js

**Expectations**
- Server is able to be launched locally on port 3001 through MySQL2
- Server log in credentials are confidential
- Server has logic to handle being pushed to a live Heroku environment
- Server has sync logic

**Comment by SirUbu** [comment]
Created branch `05-server-set-up`.

**Comment by SirUbu** [comment]
Met **Expectations**. Merged to `develop` branch.
